name: Screenshot on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start server
        run: npm run preview &
        env:
          PORT: 4173

      - name: Wait for server
        run: sleep 5

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Take screenshots
        run: |
          npx playwright screenshot --viewport-size="1280,720" http://localhost:4173 .github/assets/screenshot-01.png
          npx playwright screenshot --viewport-size="1280,720" --full-page http://localhost:4173 .github/assets/screenshot-full.png

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: .github/assets/screenshot-*.png
